### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tommygebru** [emjogall/Tea-Cozy#9]
Hey Emma, again well done on your project Teacozy, it's clear you have an excellent understanding of HTML and CSS basics. Spend a little more time reviewing/practicing upon the feedback until it clicks, and I'm confident you'll do fine.

Also keep some HTML/CSS best practices in mind when coding
[Flexbox Froggy - A game for learning CSS flexbox](https://flexboxfroggy.com/)
and also [A flexbox cheatsheet too](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
When in doubt Google it (or MDN it) 🎉

**Comment by tommygebru** [comment]
**Next steps:** you can update your project to include any of the suggestions I addressed today. Also if you choose to you can simply upload a new github repo, updated to reflect any feedback 👍  

Ok Emma keep up the good work and happy coding!

**Comment by emjogale** [comment]
Many thanks for all of your comments and suggestions and tips on things to improve on. I will spend some time looking into these suggestions. In the meantime I'm happy that I am making improvements and learning these new skills. The feedback is definitely appreciated!
